"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("series_ticker", sa.String(length=32), nullable=True),
        sa.Column("close_time", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("final_outcome_yes", sa.Boolean(), nullable=True),
        sa.Column("resolution_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starting_balance", sa.Float(), nullable=True),
        sa.Column("cash", sa.Float(), nullable=True),
        sa.Column("total_deposited", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("logged_at", sa.DateTime(), nullable=True),
        sa.Column("snapshot_ts", sa.Integer(), nullable=True),
        sa.Column("seconds_to_close", sa.Integer(), nullable=True),
        sa.Column("entry_bucket", sa.Integer(), nullable=True),
        sa.Column("p_market", sa.Float(), nullable=True),
        sa.Column("p_raw", sa.Float(), nullable=True),
        sa.Column("orderbook_mid", sa.Float(), nullable=True),
        sa.Column("orderbook_available", sa.Boolean(), nullable=True),
        sa.Column("yes_cutoff", sa.Float(), nullable=True),
        sa.Column("no_cutoff", sa.Float(), nullable=True),
        sa.Column("signal", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.String(length=128), nullable=True),
        sa.Column("agreement_region", sa.String(length=32), nullable=True),
        sa.Column("raw_features_json", sa.Text(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.Column("outcome_correct", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_signals_market_id", "signals", ["market_id"])
    op.create_table(
        "live_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("contracts", sa.Float(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("entry_price_cents", sa.Integer(), nullable=False),
        sa.Column("cost_dollars", sa.Float(), nullable=False),
        sa.Column("kalshi_order_id", sa.String(length=128), nullable=True),
        sa.Column("order_status", sa.String(length=32), nullable=True),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("entry_at", sa.DateTime(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("p_market_at_entry", sa.Float(), nullable=True),
        sa.Column("p_raw_at_entry", sa.Float(), nullable=True),
        sa.Column("agreement_region", sa.String(length=32), nullable=True),
        sa.Column("live_trade_size_setting", sa.Float(), nullable=True),
        sa.Column("error_detail", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_live_trades_ticker"), "live_trades", ["ticker"])
    op.create_table(
        "paper_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=64), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=True),
        sa.Column("contracts", sa.Float(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("entry_cost", sa.Float(), nullable=True),
        sa.Column("entry_at", sa.DateTime(), nullable=True),
        sa.Column("signal_triggered", sa.Boolean(), nullable=True),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("exit_at", sa.DateTime(), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("outcome_correct", sa.Boolean(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trade_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("market_title", sa.String(length=256), nullable=True),
        sa.Column("seconds_to_close", sa.Integer(), nullable=True),
        sa.Column("entry_bucket", sa.Integer(), nullable=True),
        sa.Column("p_market", sa.Float(), nullable=True),
        sa.Column("p_raw", sa.Float(), nullable=True),
        sa.Column("signal_mode", sa.String(length=32), nullable=True),
        sa.Column("agreement_region", sa.String(length=32), nullable=True),
        sa.Column("signal_reason", sa.String(length=256), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reversal_risk", sa.Float(), nullable=True),
        sa.Column("mispricing_gap", sa.Float(), nullable=True),
        sa.Column("btc_price", sa.Float(), nullable=True),
        sa.Column("up_price_cents", sa.Integer(), nullable=True),
        sa.Column("down_price_cents", sa.Integer(), nullable=True),
        sa.Column("chart_history_json", sa.Text(), nullable=True),
        sa.Column("raw_features_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["trade_id"], ["paper_trades.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_snapshots")
    op.drop_table("paper_trades")
    op.drop_index(op.f("ix_live_trades_ticker"), table_name="live_trades")
    op.drop_table("live_trades")
    op.drop_index("ix_signals_market_id", table_name="signals")
    op.drop_table("signals")
    op.drop_table("portfolios")
    op.drop_table("markets")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
